# Server
server:
  port: 8484

# Logging
logging:
  config: classpath:logback-dev.xml

# Application Configuration
appConfigs:
  cors:
    enabled: true
    allowedOrigins:
      - http://localhost:8686
      - http://localhost:8787