spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","mappings"]

# Application Common Configuration
appConfigs:
  cors:
    pathPattern: /api/**
    allowedMethods:
    - DELETE
    - GET
    - POST
    - PUT
    exposedHeaders:
    - Authorization
    allowCredentials: true