server:
  port: 8082

# Application Configuration
appConfigs:
  cors:
    enabled: true
    pathPattern: /api/**
    allowedOrigins:
      - http://localhost:8081
    allowedMethods:
      - DELETE
      - GET
      - POST
      - PUT
    exposedHeaders:
      - Authorization
    allowCredentials: true